spec:
  container:
  - name: doomservice
    image: /demos/doom/doom_demo_repository/doom_demo:0.1
    env:
      SNOWFLAKE_ROLE: DEMO_ROLE
      SNOWFLAKE_WAREHOUSE: DOOM_DEMO_WH
      SNOWFLAKE_DATABASE: DEMOS
      SNOWFLAKE_SCHEMA: DOOM
  endpoints:
  - name: api
    port: 8001
  - name: jupyter
    port: 8888
    public: true
  - name: doom
    port: 8080
    public: true
